\c HOUSING;
--drop the existing sequence and table if they exist
DROP SEQUENCE IF EXISTS HOUSING_SEQ;
DROP TABLE IF EXISTS HOUSING_LOCATION;

--create the sequence
CREATE SEQUENCE HOUSING_SEQ START WITH 3647 INCREMENT BY 1 MAXVALUE 2147483647 NO CYCLE;

--create the table
CREATE TABLE HOUSING_LOCATION(
    HL_ID SERIAL PRIMARY KEY,
    HL_NAME VARCHAR(255),
    HL_CITY VARCHAR(255),
    HL_STATE VARCHAR(255),
    HL_PHOTO VARCHAR(255),
    HL_AVAILABLEUNITS INTEGER,
    HL_WIFI BOOLEAN,
    HL_LAUNDRY BOOLEAN
);

INSERT INTO HOUSING_LOCATION VALUES(3647, "Rene DuBos", "Kremlin-Bicetre", "Paris", "path to image", 3, true, true);
